# syntax=docker/dockerfile:1

FROM python:3.11-alpine AS builder

WORKDIR /build

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && \
    apk add --no-cache \
        build-base \
        cargo \
        libffi-dev \
        libxml2-dev \
        libxslt-dev \
        linux-headers \
        openssl-dev \
        zlib-dev

COPY README.md MANIFEST.in pyproject.toml setup.py setup.cfg blrec.spec ./
COPY src ./src

RUN pip install -i https://mirrors.aliyun.com/pypi/simple --no-cache-dir --upgrade pip setuptools wheel && \
    pip install -i https://mirrors.aliyun.com/pypi/simple --no-cache-dir . pyinstaller==6.21.0 && \
    pyinstaller --clean --noconfirm blrec.spec

FROM alpine

WORKDIR /app
VOLUME ["/cfg", "/log", "/rec"]

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && \
    apk add --no-cache \
        ca-certificates \
        ffmpeg \
        libffi \
        libgcc \
        libstdc++ \
        libxml2 \
        libxslt \
        openssl \
        tzdata && \
    update-ca-certificates

COPY --from=builder /build/dist/blrec /usr/local/bin/blrec

ENV BLREC_DEFAULT_SETTINGS_FILE=/cfg/settings.toml \
    BLREC_DEFAULT_LOG_DIR=/log \
    BLREC_DEFAULT_OUT_DIR=/rec \
    TZ=Asia/Shanghai

EXPOSE 2233
ENTRYPOINT ["/usr/local/bin/blrec", "--host", "0.0.0.0", "--no-progress"]
CMD []
